* Cookiecutter Python
A [[https://github.com/cookiecutter/cookiecutter][cookiecutter]] template for a [[https://www.python.org/][Python]] project.

+ [[https://pydoit.org/][doit]] for task running
+ [[https://github.com/PyCQA/pylint][pylint]] and [[https://github.com/charliermarsh/ruff][ruff]] for linting
+ [[https://github.com/pytest-dev/pytest/][pytest]] and [[https://github.com/nedbat/coveragepy][coverage]] for testing
+ [[https://github.com/charliermarsh/ruff][ruff]] for formatting
+ [[https://github.com/jendrikseipp/vulture][vulture]] for dead code discovery

* Quickstart
#+BEGIN_SRC shell
cookiecutter gh:nextdoorcompany/cookiecutter-python-module
#+END_SRC

** Variables
+ *project_slug* - name of project directory to create
+ *path_to_venv* - location of virtual environment directory - bin is a subdirectory of this folder
+ *python_minor_version* - version of Python 3 to run
+ *main_file* - default first Python file in package

** Emacs
Generated [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html][.dir-locals.el]] file sets ~python-shell-virtual-root~ so ~C-c C-p~ opens a REPL in the virtual environment.  In addition, ~compile-command~ is set to use doit for linting and testing and ~M-x pdb~ will default to the main program entry point.

Use ~. eshell-activate~ to activate the virtual environment in eshell.

** Other
Use ~./<MAIN_FILE>~ in an active virtual environment to run.  See ~dodo list~ for linting and testing.

Place dependencies in the ~dependencies~ key of the ~[project]~ table of ~pyproject.toml~.

Uses [[https://github.com/astral-sh/uv][uv]] to manage virtual environment.
