[tool.pylint."messages control"]
disable = [
        "invalid-name",
        "line-too-long",
        "missing-class-docstring",
        "missing-function-docstring",
        "missing-module-docstring",
        "too-few-public-methods",
        "too-many-statements",
        "unused-import",
        "use-implicit-booleaness-not-len",
]

[tool.pylint.typecheck]
ignored-classes = ["PurePath"]

[tool.coverage.run]
omit = ["/__main__.py"]

[tool.coverage.report]
fail_under = 70
show_missing = true

[tool.ruff]
select = ["ALL"]
ignore = [
          "ANN",      # type annotations
          "COM812",   # missing trailing comma
          "D100",     # undocumented module
          "D101",     # undocumented class
          "D102",     # undocumented method
          "D103",     # undocumented function
          "D104",     # undocumented package
          "D105",     # undocumented magic method
          "D106",     # undocumented nested class
          "D107",     # undocumented init
          "D203",     # one blank line before class
          "D213",     # multi-line summary second line
          "E501",     # line too long
          "ISC001",   # implicit string concatenation on one line
          "PT006",    # paramertize-names should be tuple
          "S101",     # use of assert detected
]
